on:
  push:
     branches:
       - master

name: rmarkdown

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
      - name: Install R Markdown
        run: |
          install.packages(c("remotes", "bookdown", "formatR", "tinytex"))
          tinytex::install_tinytex()
        shell: Rscript {0}
      - name: Install package EcoFoG
        run: |
          # cairo for package gdtools
          brew install cairo
          Rscript -e 'remotes::install_github("EcoFoG/EcoFoG")'
      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Render Rmarkdown files
        run: |
          RMD_PATH=($(ls | grep '[.]Rmd$'))
          Rscript -e 'for (file in commandArgs(TRUE)) rmarkdown::render(file, "all")' ${RMD_PATH[*]}
          Rscript -e 'source("GithubPages.R")'
          echo 'theme: jekyll-theme-slate' > docs/_config.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: _docs
          path: docs/
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          # Artifact name
          name: _docs
          # Destination path
          path: docs
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          email: ${{ secrets.EMAIL }}
          build_dir: docs
          jekyll: yes
